### ISSUE TITLE
Quaternion.abs squashes dimensions

### ISSUE THREAD

**Issue by ewhitmire** [PhilJd/tf-quaternion#1]
When using a tensor of shape `[N, 4]`, the `Quaternion.abs` function produces a scalar. I would expect this to behave more like the `Quaternion.norm` function, which does preserve dimensions. An unfortunate side effect of this is that the `Quaternion.normalized` scales each quaternion by the same scalar, instead of by the norm of each quaternion. Is my understanding of the expected functionality correct?

**Comment by PhilJd** [comment]
Nice catch, thanks!
f41c7035e64c18b6cfedfbf4153b207807bcb1f3 should fix this but it usually takes a day until it's up in pypi ;)
