### ISSUE TITLE
not working with array

### ISSUE THREAD

**Issue by fangde** [PhilJd/tf-quaternion#3]
i try to rotate vectors with an array or quaterion, seems not working for me

**Comment by PhilJd** [comment]
Could you provide some sample code with the expected outcome? And which version are you using?

**Comment by fangde** [comment]
sorry, but it seems it produce two results on two system one my server 
i have the code 
import tfquaternion as tfq
import tensorflow as tf

sess=tf.Session()

q=tfq.Quaternion([[1.0,2.0,3.0,4.0],[5.0,6.0,7.0,8.0]])

print q
print 'as quaterion matrix'
matq=q.as_rotation_matrix()
print matq
print sess.run(matq)

import quaternion
import numpy as np

q=quaternion.quaternion(1.0,2.0,3.0,4.0)
print q


matq2=quaternion.as_rotation_matrix(q)


print matq2

and the results are wrong

<tfq.Quaternion '' (tf.Tensor 'Const_9:0' shape=(2, 4) dtype=float32)>
as quaterion matrix
Tensor("quaternion_as_rotation_matrix_3/stack_3:0", shape=(2, 3, 3), dtype=float32)
[[[ 0.7549019   0.01960784  0.10784315]
  [ 0.09803922  0.8039216   0.09803922]
  [ 0.04901962  0.13725491  0.872549  ]]

 [[-0.10784322  0.01960781  0.81372553]
  [ 0.8039216   0.01960778  0.25490198]
  [ 0.127451    0.84313726  0.16666669]]]
quaternion(1, 2, 3, 4)
[[-0.66666667  0.13333333  0.73333333]
 [ 0.66666667 -0.33333333  0.66666667]
 [ 0.33333333  0.93333333  0.13333333]]

but on my laptop, the results are right
I will try to update the package on my server and try it again

**Comment by fangde** [comment]
i tried to reinstall tfq on the server,but it seems not working

**Comment by fangde** [comment]
it works now, only after i upgrade tf to 1.6
but there is an warnning, I hope it does not matter for my case
s quaterion matrix
WARNING:tensorflow:From /home/fliu/anaconda2/lib/python2.7/site-packages/tfquaternion/tfquaternion.py:389: calling reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead

**Comment by PhilJd** [comment]
Sorry for the late reply, I'm travelling at the moment with limited access to internet. Thanks for investigating further! ;) Do you know which version of tensorflow you've been using before? Then I'll add a check to setup.py for the correct version number. The warning is not harmful at the moment, there's a pending pull request to fix  this.

**Comment by PhilJd** [comment]
Closing, as tf < 1.6 is rather old now.
