### ISSUE TITLE
ValueError: Can't create a quaternion from a tensor with shape (?,6). The last dimension must be 4.

### ISSUE THREAD

**Issue by kevinkit** [PhilJd/tf-quaternion#5]
Hello and thank you for this awesome repo. 

I am quite certain that this is not a direct issue with this repo, but more or less a tensorflow issue which arises here. But I hope that somebody might help me with it...

If one does the following:

`
q1 = tfq.Quaternion(y[:-3]) `

and `y` is a 6 element vector then the error will come:
`
ValueError: Can't create a quaternion form a tensor with shape (?,6). The last dimension must be 4. `

So I am wondering what would be the best way to slice an array to 4 element vector which can then be passed to the lib?

I tried it with creatin a variable, however this results in a whole other complication, since the shape must be known beforehand,... (see here: https://stackoverflow.com/questions/51493490/validate-shape-equivalent-in-keras-in-comparison-to-tensorflow )

**Comment by PhilJd** [comment]
Hi,
do you have a full working example? My current guess is that your ```y``` has a batch dimension and ```y[:-3]``` slices that dimension (and would work if you'd use ```y[:, :-4]``` instead). E.g.,
```
import numpy as np
a = np.arange(6).reshape(1, 6)
a[:-3]  # returns array([], shape=(0, 6), dtype=int64)
```
Cheers,
Phil

**Comment by kevinkit** [comment]
Thank you for your reply, this actually was my mistake and solved it. Cheers !
