### ISSUE TITLE
keyword argument `keep_dims` is deprecated; use `keepdims`

### ISSUE THREAD

**Issue by mannykoum** [PhilJd/tf-quaternion#9]
Thanks for the module but it is not compatible with TF1.13 (stable) or TF2.0 (alpha) due to the keyword argument `keep_dims` being deprecated. Please use `keepdims` in functions like `reduce_sum()`.

**Comment by mannykoum** [comment]
I see you had changed it and then changed it back to maintain backwards compatibility. I wonder if a better way to resolve this exists.

**Comment by PhilJd** [comment]
Hi @mannykoum,
I'm currently working on TF2 compatibility (plus some API changes) and I'm planning to upload a new version to pip once TF2 is out. I think this is a step where we can reasonably change keep_dims to keepdims. There are some ways to suppress the warning but I've decided against it as it makes the code more complicated and it's still compatible.

**Comment by mannykoum** [comment]
Yeah makes sense TF2 is in beta still. I'm gonna close the issue but waiting on a TF2 compatible version! thank you !

**Comment by RSchoonFPP** [comment]
haven't run a full set of tests but it appears that tfquaternion works for tf2.0 users after the tf_upgrade_v2 script is run.
